### ISSUE TITLE
running on localhost but after hosting in server not working

### ISSUE THREAD

**Issue by Gnanendra18** [gauravmehta13/razorpay_web#18]
running on localhost but after hosting in server razor pay exception is coming in page load in console in the browser.

main.dart.js:5198 Uncaught Error: MissingPluginException(No implementation found for method resync on channel razorpay_flutter)
    at Object.d (main.dart.js:5198:19)
    at main.dart.js:69696:15
    at ano.a (main.dart.js:6529:63)
    at ano.$2 (main.dart.js:40994:14)
    at amA.$1 (main.dart.js:40988:21)
    at akl.anj (main.dart.js:41582:34)
    at akl.Ii (main.dart.js:41585:13)
    at ahk.$0 (main.dart.js:41338:11)
    at Object.uM (main.dart.js:6628:40)
    at ao.ra (main.dart.js:41273:3)

**Comment by Sandeepeed** [comment]
Facing the same issue.

**Comment by Gnanendra18** [comment]
I was able to resolve the issue by using the master branch. I downloaded the master branch and replaced the example code with my project and was able to access the payment page now. I guess the library is dependent on specific flutter version. It is bundled with flutter library in the code.

**Comment by irajeshh** [comment]
Downgrading to version `1.4.2` resolves the issue.

**Comment by Sandeepeed** [comment]
For FlutterFlow users who are using Custom Code to add Razorpay Subscriptions, enable razorpay in settings and deploy the changes. That fixed it for me.

**Comment by Gaurav-CareMonitor** [comment]
Will check this, Thanks for pointing out
