### ISSUE TITLE
EVENT_PAYMENT_ERROR not working on release mode

### ISSUE THREAD

**Issue by swarup13** [gauravmehta13/razorpay_web#6]
It's working on debug mode perfectly, but in release mode it's not working, on browser console it's showing this error, can you please look into this, I really appreciate this package and your hard work, but it's really important for me.

ncaught NoSuchMethodError: method not found: 'call'
Receiver: Closure 'RazorpayFlutterPlugin_startPayment_closure0'
Arguments: [null]
    at Object.wrapException (js_helper.dart:1123:37)
    at RazorpayFlutterPlugin_startPayment_closure0.noSuchMethod$1 (core_patch.dart:66:5)
    at RazorpayFlutterPlugin_startPayment_closure0.call$1 (main.dart.js:76408:19)
    at Object.Primitives_applyFunction (js_helper.dart:848:11)
    at Object.Function_apply (core_patch.dart:86:23)
    at _callDartFunction (js_patch.dart:41:32)
    at js_patch.dart:431:55
    at checkout.js:15:30027

    
    
<img width="896" alt="Screenshot 2022-09-02 at 12 29 20 AM" src="https://user-images.githubusercontent.com/55395995/187991939-4243c511-d2fc-45ff-b8ae-043419aa4e00.png">

**Comment by gauravmehta13** [comment]
Hey @swarupbhc checking, Thanks for reporting the issue

**Comment by gauravmehta13** [comment]
Hi @swarupbhc I am not able to replicate it, is it happening on localhost as well, i tried running on local host as release build.

**Comment by swarupbhc** [comment]
Hi @gauravmehta13 just tap on the close button on release mode, it will not detect the failure

**Comment by PriyaranjanEuphotic** [comment]
Yes, I am also facing this type of error in release mode, but working fine in debug mode

**Comment by tailoristic** [comment]
Hi, Im facing the same issue
On Release build on Server

**Comment by PriyaranjanEuphotic** [comment]
> Hi, Im facing the same issue
> On Release build on Server

Try js package to implement razorpay in web

**Comment by tailoristic** [comment]
Which package? Could you please provide any resource to it

**Comment by priyaranjan12345** [comment]
you can use  [flutter_razorpay_web]( https://pub.dev/packages/flutter_razorpay_web)  which uses JS package.

**Comment by kdcyberdude** [comment]
@swarupbc Did you find any solution to this?
